import type { Metadata } from "next";
import { Inter } from "next/font/google"; 
import "../app/globals.css";
import { LayoutProvider } from "@/components/layout/LayoutProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", 
  display: "swap",
});

export const metadata: Metadata = {
  title: "PETA bencana desa Petasriharjo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased overflow-x-hidden font-sans `}>
          <LayoutProvider>
            {children}
          </LayoutProvider>
      </body>
    </html>
  );
}